import express from 'express';
import cors from 'cors';
import puppeteer from 'puppeteer';
import mongoose from 'mongoose';
import dotenv from 'dotenv';
import jwt from 'jsonwebtoken';
import bcrypt from 'bcryptjs';
import nodemailer from 'nodemailer';
import helmet from 'helmet';
import { rateLimit } from 'express-rate-limit';

dotenv.config();

const app = express();
const PORT = process.env.PORT || 3001;

// ==========================================
// EMAIL SETUP
// ==========================================
const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
        user: process.env.GMAIL_USER,
        pass: process.env.GMAIL_APP_PASSWORD
    }
});

// Throttling for alerts (1 email per hour per error type)
const alertCache = new Map();
const ALERT_THROTTLE_MS = 60 * 60 * 1000;

async function sendErrorAlert(subject, message, type = 'general') {
    const lastSent = alertCache.get(type);
    const now = Date.now();

    if (lastSent && (now - lastSent) < ALERT_THROTTLE_MS) {
        console.log(`[ALERT] Throttling alert: ${type} (Last sent ${Math.round((now - lastSent) / 1000 / 60)} mins ago)`);
        return;
    }

    try {
        // Fetch Admin Email
        let adminEmail = process.env.GMAIL_USER; // fallback
        if (mongoose.connection.readyState === 1) {
            const admin = await User.findOne({ username: 'admin' });
            if (admin?.adminEmail) adminEmail = admin.adminEmail;
        }

        const mailOptions = {
            from: `"GoldSync System Monitor" <${process.env.GMAIL_USER}>`,
            to: adminEmail,
            subject: `[SYSTEM ALERT] ${subject}`,
            html: `
                <div style="font-family: sans-serif; padding: 20px; border: 2px solid #ff4444; border-radius: 10px;">
                    <h2 style="color: #ff4444;">Critical System Alert</h2>
                    <p style="font-size: 1.1em;"><strong>Issue:</strong> ${message}</p>
                    <hr />
                    <p style="font-size: 0.8em; color: #666;">Generated by GoldSync Proxy at ${new Date().toLocaleString()}</p>
                </div>
            `
        };

        await transporter.sendMail(mailOptions);
        alertCache.set(type, now);
        console.log(`[ALERT] Error email sent: ${subject}`);
    } catch (err) {
        console.error('[ALERT] Failed to send error alert:', err.message);
    }
}

app.use((req, res, next) => {
    console.log(`[REQUEST] ${new Date().toLocaleTimeString()} ${req.method} ${req.url} (Origin: ${req.headers.origin || 'none'})`);
    next();
});

const allowedOrigins = (process.env.ALLOWED_ORIGINS || 'http://localhost:6066').split(',').map(o => o.trim());

app.use(cors({
    origin: function (origin, callback) {
        // Allow requests with no origin (like mobile apps)
        if (!origin) return callback(null, true);

        // Trim and remove trailing slash for comparison
        const cleanOrigin = origin.trim().replace(/\/$/, "");
        const isAllowed = allowedOrigins.some(o => o.trim().replace(/\/$/, "") === cleanOrigin);

        if (isAllowed) {
            return callback(null, true);
        } else {
            console.warn(`[CORS] Blocking Origin: "${origin}" (Clean: "${cleanOrigin}") - Not in: ${allowedOrigins.join(', ')}`);
            return callback(null, false);
        }
    },
    credentials: true,
    methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS'],
    allowedHeaders: ['Content-Type', 'Authorization']
}));
app.use(helmet());
app.use(express.json());

// Strict limiter for authentication & onboarding to prevent brute-force
const authLimiter = rateLimit({
    windowMs: 15 * 60 * 1000,
    max: 20, // Increased for development/demo safety
    message: { error: 'Too many attempts. Please try again in 15 minutes.' },
    standardHeaders: true,
    legacyHeaders: false,
});

// High-capacity limiter for price polling to ensure 1s updates are never blocked
const priceLimiter = rateLimit({
    windowMs: 15 * 60 * 1000,
    max: 20000, // Increased for multiple users/tabs
    standardHeaders: true,
    legacyHeaders: false,
});

// Moderate limiter for general API usage (settings, products, etc.)
const globalLimiter = rateLimit({
    windowMs: 15 * 60 * 1000,
    max: 5000, // Increased to support real-time settings sync
    standardHeaders: true,
    legacyHeaders: false,
});

// Apply limiters to specific routes
app.use('/api/auth/', authLimiter);
app.use('/api/onboarding/', authLimiter);
app.use('/api/prices', priceLimiter);
app.use('/api/', globalLimiter);

// ==========================================
// MONGODB & AUTH SETUP
// ==========================================
const MONGODB_URI = process.env.MONGODB_URI;
const JWT_SECRET = process.env.JWT_SECRET;

if (!JWT_SECRET) {
    console.error('[FATAL] JWT_SECRET is missing from .env file. Exiting.');
    process.exit(1);
}

if (MONGODB_URI && !MONGODB_URI.includes('<username>')) {
    mongoose.connect(MONGODB_URI)
        .then(() => console.log('Connected to MongoDB Atlas!'))
        .catch(err => {
            console.error('MongoDB Connection Error:', err);
            sendErrorAlert('Database Connection Failed', `Proxy could not connect to MongoDB Atlas: ${err.message}`, 'db-fail');
        });

    mongoose.connection.on('disconnected', () => {
        console.warn('MongoDB disconnected! System check...');
        setTimeout(() => {
            if (mongoose.connection.readyState !== 1) {
                sendErrorAlert('Database Offline', 'The connection to MongoDB was lost and has not recovered.', 'db-offline');
            }
        }, 30000);
    });
} else {
    console.warn('⚠️ MONGODB_URI not configured or still using placeholder. Admin features DB will not connect.');
}

const userSchema = new mongoose.Schema({
    username: { type: String, required: true, unique: true },
    passwordHash: { type: String, required: true },
    adminName: { type: String, default: '' },
    adminEmail: { type: String, default: '' }
});
const User = mongoose.model('User', userSchema);

const productSchema = new mongoose.Schema({
    category: { type: String, required: true }, // 'jewelry', 'goldBars', 'goldCoins', 'silverBars'
    name: { type: String, required: true },
    weight: { type: Number, required: true },
    weightUnit: { type: String, required: true }, // 'g' or 'oz'
    premium: { type: Number, default: 0 },
    purity: { type: Number, default: 1.0 },
    createdAt: { type: Date, default: Date.now }
});
const Product = mongoose.model('Product', productSchema);

const settingsSchema = new mongoose.Schema({
    categoryTitles: {
        goldBars: { type: String, default: 'Gold Bars' },
        goldCoins: { type: String, default: 'Gold Coins' },
        silverBars: { type: String, default: 'Silver Bars' },
        jewelry: { type: String, default: 'Jewelry' },
    },
    margin: { type: Number, default: 0 },
    marginType: { type: String, default: 'fixed', enum: ['fixed', 'percent'] },
    spotMargin: { type: Number, default: 0 },
    isLocked: { type: Boolean, default: false },
    currencyRate: { type: Number, default: 3.65 },
    marketCloseUTC: { type: String, default: '20:58' }, // Friday 11:58 PM AST = 20:58 UTC
    marketOpenUTC: { type: String, default: '23:01' },  // Monday 2:01 AM AST = Sunday 23:01 UTC
});
const Settings = mongoose.model('Settings', settingsSchema);

const onboardingSchema = new mongoose.Schema({
    completed: { type: Boolean, default: false },
    adminName: { type: String, default: '' },
    adminEmail: { type: String, default: '' },
    completedAt: { type: Date, default: null }
});
const Onboarding = mongoose.model('Onboarding', onboardingSchema);

const closingPriceSchema = new mongoose.Schema({
    gold_price: Number,
    silver_price: Number,
    closeDate: String,
    scrapedAt: { type: Date, default: Date.now }
});
const ClosingPrice = mongoose.model('ClosingPrice', closingPriceSchema);

const authenticateToken = (req, res, next) => {
    const authHeader = req.headers['authorization'];
    const token = authHeader && authHeader.split(' ')[1];
    if (!token) return res.status(401).json({ error: 'Access Denied' });

    jwt.verify(token, JWT_SECRET, (err, user) => {
        if (err) return res.status(403).json({ error: 'Invalid Token' });
        req.user = user;
        next();
    });
};

// Graceful Shutdown Handler
const shutdown = async (signal) => {
    console.log(`[SYSTEM] Received ${signal}. Shutting down gracefully...`);
    if (browser) {
        console.log('[SCRAPE] Closing browser...');
        await browser.close().catch(() => { });
    }
    if (mongoose.connection.readyState === 1) {
        console.log('[DB] Closing connection...');
        await mongoose.connection.close();
    }
    console.log('[SYSTEM] Exit.');
    process.exit(0);
};

process.on('SIGTERM', () => shutdown('SIGTERM'));
process.on('SIGINT', () => shutdown('SIGINT'));

// Global Error Handlers
process.on('uncaughtException', (err) => {
    console.error('[FATAL] Uncaught Exception:', err);
});
process.on('unhandledRejection', (reason, promise) => {
    console.error('[FATAL] Unhandled Rejection at:', promise, 'reason:', reason);
});

// Cache
let cachedPrices = null;
let lastReloadTime = 0;
let isScraping = false;
let weekendClosingFetched = false; // Track if we already scraped TradingView this weekend

// Shared Browser
let browser = null;
let goldPage = null;
let silverPage = null;
let consecutiveScrapeFailures = 0;
const MAX_SCRAPE_FAILURES = 5;

// ==========================================
// MARKET HOURS + WEEKEND LOGIC
// ==========================================
function isMarketOpen(settings) {
    const now = new Date();
    const day = now.getUTCDay();     // 0=Sun, 6=Sat
    const hour = now.getUTCHours();
    const minute = now.getUTCMinutes();
    const currentTotalMinutes = hour * 60 + minute;

    // Default values in UTC
    // Friday 23:58 AST = 20:58 UTC (1258 mins)
    // Monday 02:01 AST = Sunday 23:01 UTC (1381 mins)
    const closeStr = String(settings?.marketCloseUTC || '20:58');
    const openStr = String(settings?.marketOpenUTC || '23:01');

    const [closeH, closeM] = closeStr.includes(':') ? closeStr.split(':').map(Number) : [Number(closeStr), 0];
    const [openH, openM] = openStr.includes(':') ? openStr.split(':').map(Number) : [Number(openStr), 0];

    // Ensure they are valid numbers
    const validCloseH = isNaN(closeH) ? 20 : closeH;
    const validCloseM = isNaN(closeM) ? 58 : closeM;
    const validOpenH = isNaN(openH) ? 23 : openH;
    const validOpenM = isNaN(openM) ? 1 : openM;

    const closeMinutes = validCloseH * 60 + validCloseM;
    const openMinutes = validOpenH * 60 + validOpenM;

    // Forex/Gold markets close Friday ~UTC, reopen Sunday ~UTC
    if (day === 6) return false;                 // All Saturday
    if (day === 0 && currentTotalMinutes < openMinutes) return false;    // Sunday before open
    if (day === 5 && currentTotalMinutes >= closeMinutes) return false;   // Friday after close
    return true;
}

async function scrapeClosingPrices() {
    console.log('[WEEKEND] Scraping TradingView for closing prices...');
    let tvPage = null;
    try {
        await initBrowser();
        tvPage = await browser.newPage();
        await tvPage.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36');

        // Scrape Gold
        await tvPage.goto('https://www.tradingview.com/symbols/XAUUSD/', { waitUntil: 'networkidle2', timeout: 30000 });
        const goldData = await tvPage.evaluate(() => {
            const priceEl = document.querySelector('.js-symbol-last');
            const changeEl = document.querySelector('.js-symbol-change-direction');
            const timeEl = document.querySelector('.js-symbol-lp-time');
            const price = priceEl ? parseFloat(priceEl.innerText.trim().replace(/,/g, '')) : 0;
            let changeText = '';
            if (changeEl) {
                const spans = changeEl.querySelectorAll('span');
                changeText = spans.length > 1 ? spans[1].innerText.trim() : '';
            }
            const closeInfo = timeEl ? timeEl.innerText.trim() : '';
            return { price, changeText, closeInfo };
        });

        // Scrape Silver
        await tvPage.goto('https://www.tradingview.com/symbols/XAGUSD/', { waitUntil: 'networkidle2', timeout: 30000 });
        const silverData = await tvPage.evaluate(() => {
            const priceEl = document.querySelector('.js-symbol-last');
            const changeEl = document.querySelector('.js-symbol-change-direction');
            const price = priceEl ? parseFloat(priceEl.innerText.trim().replace(/,/g, '')) : 0;
            let changeText = '';
            if (changeEl) {
                const spans = changeEl.querySelectorAll('span');
                changeText = spans.length > 1 ? spans[1].innerText.trim() : '';
            }
            return { price, changeText };
        });

        await tvPage.close();
        tvPage = null;

        if (goldData.price && silverData.price) {
            console.log(`[WEEKEND] TradingView closing prices: Gold=$${goldData.price}, Silver=$${silverData.price}`);
            console.log(`[WEEKEND] Close info: ${goldData.closeInfo}`);

            // Persist to MongoDB
            if (mongoose.connection.readyState === 1) {
                await ClosingPrice.findOneAndUpdate({}, {
                    gold_price: goldData.price,
                    silver_price: silverData.price,
                    closeDate: goldData.closeInfo,
                    scrapedAt: new Date()
                }, { upsert: true });
            }

            return {
                gold_price: goldData.price,
                silver_price: silverData.price,
                closeDate: goldData.closeInfo
            };
        } else {
            console.warn('[WEEKEND] TradingView scrape returned 0s');
            return null;
        }

    } catch (error) {
        console.error('[WEEKEND] TradingView scrape error:', error.message);
        if (tvPage) {
            try { await tvPage.close(); } catch (e) { }
        }
        return null;
    }
}

async function initBrowser() {
    if (!browser) {
        console.log("Launching shared browser...");
        browser = await puppeteer.launch({
            headless: "new",
            args: [
                '--no-sandbox',
                '--disable-setuid-sandbox',
                '--disable-dev-shm-usage', // Docker/Container fix
                '--disable-gpu'
            ],
            ignoreHTTPSErrors: true
        });

        goldPage = await browser.newPage();
        await goldPage.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36');

        silverPage = await browser.newPage();
        await silverPage.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36');

        const goldUrl = process.env.SCRAPE_URL_GOLD || 'https://www.livepriceofgold.com/usa-gold-price.html';
        const silverUrl = process.env.SCRAPE_URL_SILVER || 'https://www.livepriceofgold.com/silver-price/us.html';

        console.log("Navigating tabs...");
        await Promise.all([
            goldPage.goto(goldUrl, { waitUntil: 'domcontentloaded', timeout: 60000 }),
            silverPage.goto(silverUrl, { waitUntil: 'domcontentloaded', timeout: 60000 })
        ]);
        console.log("Tabs ready.");
        lastReloadTime = Date.now();
    }
}

async function scrapeLoop() {
    if (isScraping) return;
    isScraping = true;

    let settings = null;
    try {
        if (mongoose.connection.readyState === 1) {
            settings = await Settings.findOne();
        }
    } catch (err) {
        console.warn('[SCRAPE] Failed to fetch settings, using defaults.');
    }

    try {
        // ==========================================
        // WEEKEND MODE: Serve frozen closing prices
        // ==========================================
        if (!isMarketOpen(settings)) {
            if (!weekendClosingFetched) {
                console.log('[WEEKEND] Market is closed. Fetching closing prices...');

                // Try TradingView scrape first
                const tvData = await scrapeClosingPrices();

                if (tvData) {
                    cachedPrices = {
                        price: tvData.gold_price,
                        bid: tvData.gold_price,
                        ask: tvData.gold_price,
                        silver_price: tvData.silver_price,
                        silver_bid: tvData.silver_price,
                        silver_ask: tvData.silver_price,
                        price_gram_24k: tvData.gold_price / 31.1035,
                        price_gram_22k: (tvData.gold_price / 31.1035) * 0.916,
                        price_gram_21k: (tvData.gold_price / 31.1035) * 0.875,
                        price_gram_18k: (tvData.gold_price / 31.1035) * 0.750,
                        timestamp: new Date().toISOString(),
                        isWeekend: true,
                        closeDate: tvData.closeDate || 'Friday Close'
                    };
                    weekendClosingFetched = true;
                    console.log('[WEEKEND] Closing prices cached successfully.');
                } else {
                    // Fallback: try loading from MongoDB
                    console.log('[WEEKEND] TradingView scrape failed, trying MongoDB...');
                    if (mongoose.connection.readyState === 1) {
                        const saved = await ClosingPrice.findOne().sort({ scrapedAt: -1 });
                        if (saved) {
                            cachedPrices = {
                                price: saved.gold_price,
                                bid: saved.gold_price,
                                ask: saved.gold_price,
                                silver_price: saved.silver_price,
                                silver_bid: saved.silver_price,
                                silver_ask: saved.silver_price,
                                price_gram_24k: saved.gold_price / 31.1035,
                                price_gram_22k: (saved.gold_price / 31.1035) * 0.916,
                                price_gram_21k: (saved.gold_price / 31.1035) * 0.875,
                                price_gram_18k: (saved.gold_price / 31.1035) * 0.750,
                                timestamp: new Date().toISOString(),
                                isWeekend: true,
                                closeDate: saved.closeDate || 'Friday Close'
                            };
                            weekendClosingFetched = true;
                            console.log('[WEEKEND] Loaded closing prices from MongoDB.');
                        }
                    }
                }
            }
            // Poll infrequently on weekends (every 60s to detect Monday reopen)
            return;
        }

        // ==========================================
        // WEEKDAY MODE: Normal live scraping
        // ==========================================
        // Reset weekend flag when market reopens
        if (weekendClosingFetched) {
            weekendClosingFetched = false;
            console.log('[WEEKDAY] Market reopened. Resuming live scraping...');
        }

        await initBrowser();

        const timestamp = Date.now();

        // Safety: Full reload every 5 minutes (300000ms) to clear memory/stuck scripts
        if (timestamp - lastReloadTime > 300000) {
            console.log("Performing periodic page reload...");
            await Promise.all([
                goldPage.reload({ waitUntil: 'domcontentloaded', timeout: 30000 }),
                silverPage.reload({ waitUntil: 'domcontentloaded', timeout: 30000 })
            ]);
            lastReloadTime = timestamp;
        }

        // Logic Change: DO NOT RELOAD EVERY TIME!
        // Just read the DOM. The site updates via JS WebSocket/Long-polling.

        if (goldPage.isClosed() || silverPage.isClosed()) {
            throw new Error("Page was closed or detached");
        }

        // Extract Gold
        const goldData = await goldPage.evaluate(() => {
            const getPrice = (selector) => {
                const el = document.querySelector(selector);
                return el ? parseFloat(el.innerText.trim().replace(/,/g, '')) : 0;
            };
            return {
                price: getPrice('[data-price="XAUUSD"]'),
                bid: getPrice('[data-price="XAUUSD_BID"]'),
                ask: getPrice('[data-price="XAUUSD_ASK"]')
            };
        });

        // Extract Silver
        const silverData = await silverPage.evaluate(() => {
            const getPrice = (selector) => {
                const el = document.querySelector(selector);
                return el ? parseFloat(el.innerText.trim().replace(/,/g, '')) : 0;
            };
            return {
                price: getPrice('[data-price="XAGUSD"]'),
                bid: getPrice('[data-price="XAGUSD_BID"]'),
                ask: getPrice('[data-price="XAGUSD_ASK"]')
            };
        });

        // Update Cache
        if (goldData.price || silverData.price) {
            // Only log if values changed (reduce noise)
            const oldPrice = cachedPrices ? cachedPrices.price : 0;
            if (goldData.price !== oldPrice) {
                console.log(`[${new Date().toLocaleTimeString()}] PRICE UPDATE: Gold=${goldData.price}, Silver=${silverData.price}`);
            } else {
                console.log("No change..."); // Optional debug
            }

            cachedPrices = {
                price: goldData.price,
                bid: goldData.bid,
                ask: goldData.ask,
                silver_price: silverData.price,
                silver_bid: silverData.bid,
                silver_ask: silverData.ask,
                price_gram_24k: goldData.price / 31.1035,
                price_gram_22k: (goldData.price / 31.1035) * 0.916,
                price_gram_21k: (goldData.price / 31.1035) * 0.875,
                price_gram_18k: (goldData.price / 31.1035) * 0.750,
                timestamp: new Date().toISOString(),
                isWeekend: false
            };
            consecutiveScrapeFailures = 0; // Reset on success
        } else {
            console.warn('[SCRAPE] Extracted values are 0 or null, keeping old cache.');
            consecutiveScrapeFailures++;
        }
    } catch (error) {
        console.error('[SCRAPE] Error during scrape loop:', error.message);
        consecutiveScrapeFailures++;
        if (consecutiveScrapeFailures >= MAX_SCRAPE_FAILURES) {
            sendErrorAlert(
                'Live Scraper Failure',
                `The live gold/silver price scraper has failed ${consecutiveScrapeFailures} times in a row. Final check: ${error.message}`,
                'scrape-fail'
            );
            console.error(`[SCRAPE] Max consecutive scrape failures reached. Restarting browser.`);
            if (browser) await browser.close().catch(() => { });
            browser = null; // Force re-initialization
        }
    } finally {
        isScraping = false;
        // Weekend: poll every 60s; Weekday: poll every 1s
        const nextInterval = isMarketOpen(settings) ? 1000 : 60000;
        setTimeout(scrapeLoop, nextInterval);
    }
}

// ==========================================
// ADMIN API ROUTES
// ==========================================

app.post('/api/auth/login', async (req, res) => {
    const { username, password } = req.body;

    try {
        const userCount = await User.countDocuments();
        if (userCount === 0) {
            // No users exist - this happens before onboarding.
            // We allow admin/admin ONLY if onboarding isn't done yet and it's a fresh install.
            let onboarding = await Onboarding.findOne();
            if (!onboarding || !onboarding.completed) {
                if (username === 'admin' && password === 'admin') {
                    const hash = await bcrypt.hash('admin', 10);
                    await new User({ username: 'admin', passwordHash: hash }).save();
                    console.log('Seeded initial fallback admin user.');
                }
            }
        }

        const user = await User.findOne({ username });
        if (!user) return res.status(400).json({ error: 'Invalid credentials' });

        const validPassword = await bcrypt.compare(password, user.passwordHash);
        if (!validPassword) return res.status(400).json({ error: 'Invalid credentials' });

        const token = jwt.sign({ id: user._id, username: user.username }, JWT_SECRET, { expiresIn: '24h' });
        console.log(`[LOGIN] User ${username} logged in. adminName: ${user.adminName}`);
        res.json({
            token,
            username: user.username,
            adminName: user.adminName || '',
            adminEmail: user.adminEmail || ''
        });
    } catch (err) {
        res.status(500).json({ error: 'Server error', details: err.message });
    }
});

app.get('/api/onboarding/status', async (req, res) => {
    try {
        let onboarding = await Onboarding.findOne();
        if (!onboarding) {
            onboarding = await new Onboarding().save();
        }
        res.json({ completed: onboarding.completed, adminName: onboarding.adminName, adminEmail: onboarding.adminEmail });
    } catch (err) {
        res.status(500).json({ error: 'Failed to fetch onboarding status' });
    }
});

app.post('/api/onboarding/complete', async (req, res) => {
    try {
        const { adminName, adminEmail, password, spotMargin, margin, marginType } = req.body;

        // Save onboarding info
        let onboarding = await Onboarding.findOne();
        if (!onboarding) onboarding = new Onboarding();
        onboarding.completed = true;
        onboarding.adminName = adminName || '';
        onboarding.adminEmail = adminEmail || '';
        onboarding.completedAt = new Date();
        await onboarding.save();

        // Also create/update the main Admin user with these details
        const hash = await bcrypt.hash(password || 'admin', 10);
        let adminUser = await User.findOne({ username: 'admin' });
        if (!adminUser) {
            adminUser = new User({ username: 'admin', passwordHash: hash });
        }
        adminUser.adminName = adminName || '';
        adminUser.adminEmail = adminEmail || '';
        adminUser.passwordHash = hash;
        await adminUser.save();
        console.log(`[ONBOARDING] Admin user updated. Name: ${adminUser.adminName}, Email: ${adminUser.adminEmail}`);

        // 4. Send Welcome Email
        try {

            const mailOptions = {
                from: `"GoldSync" <${process.env.GMAIL_USER}>`,
                to: adminEmail,
                subject: 'Welcome to GoldSync Live - Setup Complete',
                html: `
                    <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e0e0e0; border-radius: 10px;">
                        <h2 style="color: #ab8c56;">Welcome, ${adminName}!</h2>
                        <p>Your GoldSync Live Visual Manager setup is complete. You can now manage your live dashboard and assets.</p>
                        <div style="background: #f9f9f9; padding: 15px; border-radius: 5px; margin: 20px 0;">
                            <p style="margin: 0;"><strong>Username:</strong> admin</p>
                            <p style="margin: 5px 0 0;"><strong>Access URL:</strong> <a href="http://localhost:6066/login" style="color: #ab8c56;">Go to Admin Panel</a></p>
                        </div>
                        <p style="font-size: 0.8em; color: #666;">This is an automated notification from your local GoldSync Proxy server.</p>
                    </div>
                `
            };

            await transporter.sendMail(mailOptions);
            console.log(`[EMAIL] Welcome email sent to ${adminEmail}`);
        } catch (emailErr) {
            console.error('[EMAIL] Failed to send welcome email:', emailErr.message);
            // Don't fail the whole request if email fails
        }
        console.log(`[ONBOARDING] Admin user saved. Name: ${adminName}, Email: ${adminEmail}`);

        // Apply initial settings if provided
        let settings = await Settings.findOne();
        if (!settings) settings = new Settings();
        if (spotMargin !== undefined) settings.spotMargin = spotMargin;
        if (margin !== undefined) settings.margin = margin;
        if (marginType !== undefined) settings.marginType = marginType;
        await settings.save();

        // Seed default products if none exist
        const productCount = await Product.countDocuments();
        if (productCount === 0) {
            const seedProducts = [
                { name: '1g', category: 'goldBars', weight: 1, weightUnit: 'g', premium: 0, purity: 1.0 },
                { name: '5g', category: 'goldBars', weight: 5, weightUnit: 'g', premium: 0, purity: 1.0 },
                { name: '10g', category: 'goldBars', weight: 10, weightUnit: 'g', premium: 0, purity: 1.0 },
                { name: '1 oz', category: 'goldBars', weight: 1, weightUnit: 'oz', premium: 0, purity: 1.0 },
                { name: '100g', category: 'goldBars', weight: 100, weightUnit: 'g', premium: 0, purity: 1.0 },
                { name: '1 kg', category: 'goldBars', weight: 1000, weightUnit: 'g', premium: 0, purity: 1.0 },
                { name: '1/4 oz', category: 'goldCoins', weight: 0.25, weightUnit: 'oz', premium: 0, purity: 1.0 },
                { name: '1/2 oz', category: 'goldCoins', weight: 0.5, weightUnit: 'oz', premium: 0, purity: 1.0 },
                { name: '1 oz', category: 'goldCoins', weight: 1, weightUnit: 'oz', premium: 0, purity: 1.0 },
                { name: '1 oz', category: 'silverBars', weight: 1, weightUnit: 'oz', premium: 0, purity: 1.0 },
                { name: '100g', category: 'silverBars', weight: 100, weightUnit: 'g', premium: 0, purity: 1.0 },
                { name: '1 kg', category: 'silverBars', weight: 1000, weightUnit: 'g', premium: 0, purity: 1.0 },
                { name: '24K', category: 'jewelry', weight: 1, weightUnit: 'g', premium: 0, purity: 1.0 },
                { name: '22K', category: 'jewelry', weight: 1, weightUnit: 'g', premium: 0, purity: 22 / 24 },
                { name: '21K', category: 'jewelry', weight: 1, weightUnit: 'g', premium: 0, purity: 21 / 24 },
                { name: '18K', category: 'jewelry', weight: 1, weightUnit: 'g', premium: 0, purity: 18 / 24 },
            ];
            await Product.insertMany(seedProducts);
            console.log('Onboarding: Seeded 16 default products.');
        }

        res.json({ success: true });
    } catch (err) {
        res.status(500).json({ error: 'Failed to complete onboarding', details: err.message });
    }
});

app.get('/api/products', async (req, res) => {
    try {
        if (mongoose.connection.readyState !== 1) {
            return res.json([]);
        }
        const products = await Product.find().lean();
        res.json(products);
    } catch (err) {
        res.status(500).json({ error: 'Failed to fetch custom products' });
    }
});

app.post('/api/products', authenticateToken, async (req, res) => {
    try {
        const product = new Product(req.body);
        await product.save();
        res.status(201).json(product);
    } catch (err) {
        res.status(400).json({ error: 'Failed to save product', details: err.message });
    }
});

app.put('/api/products/:id', authenticateToken, async (req, res) => {
    try {
        const updatedProduct = await Product.findByIdAndUpdate(req.params.id, req.body, { new: true });
        if (!updatedProduct) return res.status(404).json({ error: 'Product not found' });
        res.json(updatedProduct);
    } catch (err) {
        res.status(400).json({ error: 'Failed to update product', details: err.message });
    }
});

app.delete('/api/products/:id', authenticateToken, async (req, res) => {
    try {
        await Product.findByIdAndDelete(req.params.id);
        res.json({ success: true, message: 'Product deleted' });
    } catch (err) {
        res.status(500).json({ error: 'Failed to delete product' });
    }
});

// Settings API
app.get('/api/settings', async (req, res) => {
    try {
        if (mongoose.connection.readyState !== 1) {
            return res.json({ categoryTitles: {} });
        }
        let settings = await Settings.findOne();
        if (!settings) {
            settings = await new Settings().save();
        }
        res.json(settings);
    } catch (err) {
        res.status(500).json({ error: 'Failed to fetch settings' });
    }
});

app.put('/api/settings', authenticateToken, async (req, res) => {
    try {
        let settings = await Settings.findOne();
        if (!settings) {
            settings = new Settings();
        }

        if (req.body.categoryTitles) {
            settings.categoryTitles = { ...settings.categoryTitles, ...req.body.categoryTitles };
        }
        if (req.body.margin !== undefined) {
            settings.margin = req.body.margin;
        }
        if (req.body.marginType !== undefined) {
            settings.marginType = req.body.marginType;
        }
        if (req.body.spotMargin !== undefined) {
            settings.spotMargin = req.body.spotMargin;
        }
        if (req.body.isLocked !== undefined) {
            settings.isLocked = req.body.isLocked;
        }
        if (req.body.currencyRate !== undefined) {
            settings.currencyRate = req.body.currencyRate;
        }
        if (req.body.marketCloseUTC !== undefined) {
            settings.marketCloseUTC = req.body.marketCloseUTC;
        }
        if (req.body.marketOpenUTC !== undefined) {
            settings.marketOpenUTC = req.body.marketOpenUTC;
        }

        await settings.save();
        res.json(settings);
    } catch (err) {
        res.status(500).json({ error: 'Failed to update settings', details: err.message });
    }
});

app.post('/api/auth/profile', authenticateToken, async (req, res) => {
    try {
        const { adminName, adminEmail, password } = req.body;
        const user = await User.findById(req.user.id);
        if (!user) return res.status(404).json({ error: 'User not found' });

        if (adminName !== undefined) user.adminName = adminName;
        if (adminEmail !== undefined) user.adminEmail = adminEmail;
        if (password) {
            user.passwordHash = await bcrypt.hash(password, 10);
        }

        await user.save();
        res.json({
            success: true,
            adminName: user.adminName,
            adminEmail: user.adminEmail
        });
    } catch (err) {
        res.status(500).json({ error: 'Failed to update profile' });
    }
});

app.post('/api/system/test-alert', authenticateToken, async (req, res) => {
    try {
        await sendErrorAlert('Test Verification', 'This is a test alert triggered manually from the Admin Panel to verify email routing.', 'test-' + Date.now());
        res.json({ success: true, message: 'Test alert sent' });
    } catch (err) {
        res.status(500).json({ error: 'Failed to send test alert' });
    }
});

app.post('/api/system/factory-reset', authenticateToken, async (req, res) => {
    try {
        // Clear all relevant collections
        await Onboarding.deleteMany({});
        await Settings.deleteMany({});
        await User.deleteMany({});
        await Product.deleteMany({});
        await ClosingPrice.deleteMany({});

        console.log('FACTORY RESET: All data wiped.');
        res.json({ success: true, message: 'System reset to factory defaults' });
    } catch (err) {
        res.status(500).json({ error: 'Factory reset failed', details: err.message });
    }
});


// API Endpoint
app.get('/api/prices', (req, res) => {
    if (cachedPrices) {
        res.json(cachedPrices);
    } else {
        if (isScraping && !cachedPrices) {
            res.status(503).json({ error: "Initializing prices..." });
        } else {
            res.status(500).json({ error: "No price data available" });
        }
    }
});

// Root
app.get('/', (req, res) => {
    res.send('Gold Price Proxy (Realtime DOM Polling) Running! Data is cached in background.');
});

// Start Server
const server = app.listen(PORT, '0.0.0.0', () => {
    console.log(`Proxy server running on port ${PORT} (0.0.0.0)`);
    console.log(`Local Access: http://localhost:${PORT}`);
    console.log(`Network Access: http://192.168.18.229:${PORT}`);
    console.log("Starting scrape loop...");
    // Start scraping AFTER server is listening
    scrapeLoop();
});

server.on('error', (err) => {
    console.error('Server Error:', err);
});
